apiVersion: k8s.amaiz.com/v1alpha1
kind: Redis
metadata:
  labels:
    app.kubernetes.io/instance: shareed2k
    app.kubernetes.io/name: redis
  name: shareed2k
  namespace: redis
status:
  master: redis-api-gateway-1
  replicas: 3
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: shareed2k
                app.kubernetes.io/name: redis
            topologyKey: kubernetes.io/hostname
          weight: 100
  annotations:
    prometheus.io/port: '9121'
    prometheus.io/scrape: 'true'
  config:
    client-output-buffer-limit: slave 0 0 0
    maxmemory: 256mb
    maxmemory-policy: volatile-ttl
    repl-backlog-size: 64mb
    save: 600 1
  exporter:
    image: oliver006/redis_exporter:v1.28.0
  initContainers:
    - args:
        - |
          sysctl -w net.core.somaxconn=1024
          exit 0
      command:
        - sh
        - '-c'
      image: busybox
      name: sysctl
      securityContext:
        privileged: true
        runAsUser: 0
  redis:
    image: redis:6-alpine
    initialDelaySeconds: 10
    resources:
      limits:
        memory: 384Mi
  replicas: 3
