apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redis-operator
resources:
- Namespace.yaml
- crds/k8s_v1alpha1_redis_crd.yaml
- ClusterRole.yaml
- ClusterRoleBinding.yaml
- ServiceAccount.yaml
- Deployment.yaml
